version: '3.5'

services:
  kafka-exporter:
    image: ${IMAGE_NAME:-danielqsj/kafka-exporter}:${IMAGE_TAG:-latest}
    command:
      - kafka.server=${KAFKA_SERVER_0}
      - kafka.server=${KAFKA_SERVER_1}
      - kafka.server=${KAFKA_SERVER_2}
      - kafka.version=${KAFKA_VERSION}
      - web.listen-address=${PORT}
      - log.level=${LOG_LEVEL}
    networks:
      - kafka-net
      - metric-net
    healthcheck:
      test: wget --spider http://localhost:${PORT}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
        window: 1m
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          memory: 205M

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    external: true
