version: '3.5'

services:
  kafka-exporter:
    image: ${IMAGE_NAME:-danielqsj/kafka-exporter}:${IMAGE_TAG:-latest}
    command:
      - --kafka.server=${KAFKA_SERVER_0}
      - --kafka.server=${KAFKA_SERVER_1}
      - --kafka.server=${KAFKA_SERVER_2}
      - --kafka.version=${KAFKA_VERSION}
      - --web.listen-address=:${PORT}
      - --log.level=${LOG_LEVEL}
    networks:
      kafka-net:
      metric-net:
    healthcheck:
      test: wget --spider -q http://localhost:${PORT}
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-30s}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-32M}

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    driver: ${KAFKA_NET_DRIVER:-overlay}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true
